name: Short Bio of INES.IA Researchers
description: Please fill all the required fields for your bio to be included in the website.
title: "[ShortBio]: "
labels: ["enhancement"]
assignees:
  - rbonifacio
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Please fill in your information
  - type: input
    id: name
    attributes:
      label: Name
      description: Please include your name as you wish to be shown on the website.
    validations:
      required: true
  - type: dropdown
    id: role
    attributes:
      label: Current role in INES.IA
      options:
        - Faculty
        - Post-Doc Researcher
        - PhD Student
        - Masters Student
        - Undergraduate Student
    validations:
      required: true
  - type: input
    id: affiliation
    attributes:
      label: Affiliation
      description: Please include your current affiliation in the format (Full Institution Name - ACRONYM).
    validations:
      required: true
  - type: textarea
    id: short-bio
    attributes:
      label: Short Bio
      description: Please include your short bio here.
    validations:
      required: true
  - type: input
    id: orcid
    attributes:
      label: ORCID
      description: Please include the link to your ORCID website.
    validations:
      required: true
  - type: input
    id: lattes
    attributes:
      label: CV Lattes
      description: Please include the link to your Lattes.
    validations:
      required: true
  - type: input
    id: personal-webpage
    attributes:
      label: Personal Webpage
      description: Please include the link to your personal website (if any).
    validations:
      required: false
