#!/usr/bin/env python3
"""Convert bibliography/publications.bib into data/publications.yaml.

No third-party dependencies (bibtexparser isn't installed in this repo's
environment) -- this is a small hand-rolled parser covering the subset of
BibTeX actually used in publications.bib: @type{key, field = {value}, ...}
entries, with brace- or quote-delimited or bare values.

Usage: python3 scripts/bib_to_yaml.py
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BIB_PATH = ROOT / "bibliography" / "publications.bib"
YAML_PATH = ROOT / "data" / "publications.yaml"


def strip_comments(text):
    return re.sub(r"(?m)^%.*$", "", text)


def split_entries(text):
    """Yield (entry_type, raw_body) for each @type{ ... } block, matching
    braces by depth so nested {} inside field values doesn't break early."""
    for m in re.finditer(r"@(\w+)\s*\{", text):
        entry_type = m.group(1)
        start = m.end()
        depth = 1
        i = start
        while i < len(text) and depth > 0:
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
            i += 1
        yield entry_type, text[start:i - 1]


def split_fields(body):
    """Split 'key, field = {val}, field = "val", field = bare, ...' into
    (cite_key, {field: value})."""
    comma = body.index(",")
    cite_key = body[:comma].strip()
    rest = body[comma + 1:]

    fields = {}
    i = 0
    n = len(rest)
    while i < n:
        m = re.match(r"\s*,?\s*([A-Za-z][\w-]*)\s*=\s*", rest[i:])
        if not m:
            break
        name = m.group(1).lower()
        i += m.end()
        if i >= n:
            break
        if rest[i] == "{":
            depth = 1
            j = i + 1
            while j < n and depth > 0:
                if rest[j] == "{":
                    depth += 1
                elif rest[j] == "}":
                    depth -= 1
                j += 1
            value = rest[i + 1:j - 1]
            i = j
        elif rest[i] == '"':
            j = rest.index('"', i + 1)
            value = rest[i + 1:j]
            i = j + 1
        else:
            j = i
            while j < n and rest[j] not in ",}":
                j += 1
            value = rest[i:j].strip()
            i = j
        fields[name] = " ".join(value.split())
    return cite_key, fields


def format_authors(raw):
    people = [p.strip() for p in raw.split(" and ") if p.strip()]
    names = []
    for p in people:
        if "," in p:
            last, first = p.split(",", 1)
            names.append(f"{first.strip()} {last.strip()}")
        else:
            names.append(p)
    return ", ".join(names)


def yaml_escape(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')


def main():
    if not BIB_PATH.exists():
        print(f"error: {BIB_PATH} not found", file=sys.stderr)
        sys.exit(1)

    text = strip_comments(BIB_PATH.read_text(encoding="utf-8"))
    entries = []
    for entry_type, body in split_entries(text):
        cite_key, fields = split_fields(body)

        title = fields.get("title", "")
        authors = format_authors(fields.get("author", ""))
        year = fields.get("year", "")

        if fields.get("archiveprefix", "").lower() == "arxiv":
            venue = "arXiv"
        else:
            venue = fields.get("journal") or fields.get("booktitle") or ""

        link = fields.get("url")
        if not link and fields.get("eprint") and venue == "arXiv":
            link = f"https://arxiv.org/abs/{fields['eprint']}"

        related_type, related_slug = "", ""
        if "relatedto" in fields and ":" in fields["relatedto"]:
            related_type, related_slug = fields["relatedto"].split(":", 1)
            related_type = related_type.strip()
            related_slug = related_slug.strip()

        entries.append({
            "key": cite_key,
            "title": title,
            "authors": authors,
            "venue": venue,
            "year": year,
            "link": link or "",
            "relatedType": related_type,
            "relatedSlug": related_slug,
        })

    lines = [
        "# Generated by scripts/bib_to_yaml.py from bibliography/publications.bib",
        "# Do not edit by hand -- edit the .bib file and re-run the script.",
        "publications:",
    ]
    for e in entries:
        lines.append(f'  - key: "{yaml_escape(e["key"])}"')
        lines.append(f'    title: "{yaml_escape(e["title"])}"')
        lines.append(f'    authors: "{yaml_escape(e["authors"])}"')
        lines.append(f'    venue: "{yaml_escape(e["venue"])}"')
        lines.append(f'    year: {e["year"]}')
        lines.append(f'    link: "{yaml_escape(e["link"])}"')
        lines.append(f'    relatedType: "{yaml_escape(e["relatedType"])}"')
        lines.append(f'    relatedSlug: "{yaml_escape(e["relatedSlug"])}"')

    YAML_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(entries)} publications to {YAML_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
